### ISSUE TITLE
Login fails with "HTTP Code 404: Not Found" when using a complex password

### ISSUE THREAD

**Issue by zcm** [hammem/monarchmoney#98] opened 2024-04-03 18:11 UTC
Passwords such as the following cause login to fail with a 404 (not my real password, but an example that actually fails):

```
Ab[1C*[Def`'&]2g,/H%3I}J'_KLmn`o
```

I had to change my password to alphanumeric (i.e., no symbols) to get login to work properly. The example password has both quotes and a forward slash, so that might be the cause.

**Comment by grablair** [comment] 2024-04-03 18:44
Can you give us a code example that results in the 404? (use a dummy email and replace your password w/ that dummy password in the example)

I just want to make sure I know how you're inputting the password into the login method; whether it be with double quotes, single quotes, multi-line, variable, etc.

**Comment by grablair** [comment] 2024-04-03 19:04
I just changed my own password to the exact example you supplied (and changed it back) and I was able to successfully login without error.

FWIW a 404 on login means "no account with that username and password combination exists", not "this endpoint / webpage doesn't exist"

**Comment by hammem** [comment] 2024-04-14 20:11
@zcm , based on @grablair not being able to reproduce this, I'm inclined to close the issue.  please let us know if this is still happening.

**Comment by hammem** [comment] 2024-05-10 22:59
Closing, since we can't reproduce it.

**Closed** 2024-05-10 23:00 UTC
Labels: bug
