### ISSUE TITLE
Missing transactions

### ISSUE THREAD

**Issue by emann3** [hammem/monarchmoney#46] opened 2023-11-20 18:20 UTC
if MonarchMoney marks a transaction as Recurring, it does not come down as part of the get_transactions function and you have to call get_transactions twice: once with is_recurring=true and once with it as false in order to get all transactions.

Is there a way to make get_transactions NOT filter on recurring if thats what the user wants?

Similar issue on all of the Boolean parameters to get_transactions: has_attachments, has_notes, hidden_from_reports, is_split

But only recurring seems to be something that MonarchMoney sets by itself on a transaction, the rest get downloaded unless I have done something to the transaction, so I can control that.

**Comment by grablair** [comment] 2023-11-20 19:03
Hmm, IMO the default `get_transactions` (i.e. with no filter args) should return _all_ transactions, so this sounds like unintended behavior.

We default to `False` for a number of filters:

https://github.com/hammem/monarchmoney/blob/6c66ee78bec2f963054600813d79ec1a8824c296/monarchmoney/monarchmoney.py#L298-L313

And always add them as filters in the API call variables:

https://github.com/hammem/monarchmoney/blob/6c66ee78bec2f963054600813d79ec1a8824c296/monarchmoney/monarchmoney.py#L395-L410

These should probably be `None` and then we should not add them as filters in the API call variables if they aren't specified by the user.

**Comment by grablair** [comment] 2023-11-21 19:47
Will be fixed by: https://github.com/hammem/monarchmoney/pull/41

**Comment by hammem** [comment] 2023-11-22 22:36
This was fixed in #41 and with the v0.1.5 release, it's available in pypi.  Just `pip install --update monarchmoney` to get the latest!

**Closed by hammem** 2023-11-22 22:36 UTC
Labels: bug
